import { LeaderboardEntry } from '@/types';

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  {
    rank: 1,
    walletAddress: 'GAEQ5IUNQTW36XMQF6MR2VWKPG3JOF6IKEGAD2JQ6OUNKTUVBAIE5AO3',
    displayName: 'Verra Climate Action Corp',
    totalRetiredTons: 1450,
    totalXlmSpent: 21750,
    badges: ['Net-Zero Pioneer', 'Verra Partner', 'Top Offsetter 2026'],
    lastActive: Date.now() - 1000 * 60 * 45,
    verifiedOrg: true,
  },
  {
    rank: 2,
    walletAddress: 'GBQHHOH72M522QBF7SMY57JH6FIN7YKTZUWSO4S5IFBXV3B7FI2UQLIQ',
    displayName: 'Amazonia Reforestation Fund',
    totalRetiredTons: 1120,
    totalXlmSpent: 16800,
    badges: ['Mangrove Guardian', 'Gold Standard Validator'],
    lastActive: Date.now() - 1000 * 60 * 120,
    verifiedOrg: true,
  },
  {
    rank: 3,
    walletAddress: 'GBYHKEYCYLCF6JTM3FPCVGOVVQS4JU7FEKGTVRQT7CWJHHDK6F5MW4UV',
    displayName: 'Nordic Clean Energy Alliance',
    totalRetiredTons: 890,
    totalXlmSpent: 13350,
    badges: ['Wind Power Champion', 'ESG Leader'],
    lastActive: Date.now() - 1000 * 60 * 300,
    verifiedOrg: true,
  },
  {
    rank: 4,
    walletAddress: 'GDGU46X55N4SU5B6TARBUU6R6XHTIQNQQTBPDLYZ6JRO44J4H6EHVYKB',
    displayName: 'Global Solar Offsets Ltd',
    totalRetiredTons: 740,
    totalXlmSpent: 11100,
    badges: ['Solar Pioneer', 'ACR Certified'],
    lastActive: Date.now() - 1000 * 60 * 600,
    verifiedOrg: true,
  },
  {
    rank: 5,
    walletAddress: 'GDUQ3DXGSNRGPNNGHLKXLSVPRC3V2PAYMP6ITW3ICSRLF64KVOTPA6AT',
    displayName: 'Stellar Green Node Validator',
    totalRetiredTons: 620,
    totalXlmSpent: 9300,
    badges: ['Carbon Neutral Node', 'Stellar Builder'],
    lastActive: Date.now() - 1000 * 60 * 900,
    verifiedOrg: true,
  },
  {
    rank: 6,
    walletAddress: 'GCX6WRPXX5JWFZQPAE7DDNPNXGGBYS3TEUPWI3N3EYSL5MCUG5EBE2VW',
    displayName: 'BioChar Climate Labs',
    totalRetiredTons: 510,
    totalXlmSpent: 7650,
    badges: ['Direct Air Capture', 'Research Partner'],
    lastActive: Date.now() - 1000 * 60 * 1440,
    verifiedOrg: true,
  },
  {
    rank: 7,
    walletAddress: 'GDP5AKZGPSJ5ME5TVRLLJRR3AX357NVBVQAT56HUGOS5WVJBU4VLPF4K',
    displayName: 'Elena Rostova (ESG Lead)',
    totalRetiredTons: 430,
    totalXlmSpent: 6450,
    badges: ['Community Ambassador'],
    lastActive: Date.now() - 1000 * 60 * 2880,
    verifiedOrg: false,
  },
  {
    rank: 8,
    walletAddress: 'GB4YOMNRLDL5THQ5WSKPMBBNUJIU4LE36WJ2VYC235W6NRFPAJVDC7L5',
    displayName: 'Pacific Blue Carbon Reserve',
    totalRetiredTons: 380,
    totalXlmSpent: 5700,
    badges: ['Coastal Protection'],
    lastActive: Date.now() - 1000 * 60 * 4320,
    verifiedOrg: true,
  },
];
